spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://admin:password@localhost:8888

---

spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://admin:password@config-server:8888
