version: '3'
services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 3s
      timeout: 5s
      retries: 5

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/actuator/health" ]
      interval: 3s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      discovery-server:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - backend-network
    depends_on:
      discovery-server:
        condition: service_healthy

  probability-service:
    build: ./probability-service
    container_name: probability-service
    networks:
      - backend-network
    depends_on:
      discovery-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - backend-network
    depends_on:
      discovery-server:
        condition: service_healthy

networks:
  backend-network:
    driver: bridge
