spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://admin:password@config-server:8888

jwt:
  secret: fEDYiKuYlRKW/NscG8DEFqtIyb2Vo0Y3wEmGMEZ7oSLuoBakNBPN1BZvkBtYOsmIHljKX5BJmJLKSiRsZYaq6g==
  expiration: 36000000

#spring:
#  application:
#    name: discovery-service
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL}
