spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://admin:password@config-server:8888


#spring:
#  application:
#    name: discovery-service
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL}
