spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://admin:password@localhost:8888


#spring:
#  application:
#    name: api-gateway
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL}
