encrypt:
  key: ${ENCRYPT_KEY}

security:
  user:
    username: ${CONFIG_USERNAME}
    password: ${CONFIG_PASSWORD}

server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH}