server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: swagger-server
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/swagger-ui/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: log-service
          uri: lb://LOG-SERVICE
          predicates:
            - Path=/logs/**
        - id: kid-service
          uri: lb://KID-SERVICE
          predicates:
            - Path=/kids/**
        - id: word-service
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/words/**
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/games/**
        - id: collection-service
          uri: lb://COLLECTION-SERVICE
          predicates:
            - Path=/collections/**
        - id: probability-service
          uri: lb://PROBABILITY-SERVICE
          predicates:
            - Path=/api/probability/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**