server:
  port: 8080

spring:
  cloud:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins:
            - 'http://localhost:5173'
          allow-credentials: true
          allowedHeaders: '*'
          allowedMethods:
            - PUT
            - GET
            - POST
            - DELETE
            - OPTIONS
    gateway:
      routes:
        - id: swagger-server
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/swagger-ui/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: log-service
          uri: lb://LOG-SERVICE
          predicates:
            - Path=/api/logs/**
        - id: kid-service
          uri: lb://KID-SERVICE
          predicates:
            - Path=/api/kids/**
        - id: word-service
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/api/words/**
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/games/**
        - id: collection-service
          uri: lb://COLLECTION-SERVICE
          predicates:
            - Path=/api/collections/**
        - id: probability-service
          uri: lb://PROBABILITY-SERVICE
          predicates:
            - Path=/api/probability/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**