spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "{cipher}b3cf5b5d4aa1cdc2ab7db75e869f7d97e079cebb874df26f78cf6ea8b304523f323027c80ea7d974d78abde3cbafd99a48282ed80fe9150b34153e0b95db6bae"
    username: "{cipher}2cdde92bd8448500aad5134fef09e8aa84010f585e189f27b8ab7b4b05c38d7b"
    password: "{cipher}99d38a6d7465db51b45f0739e83e925c90eeb39d8a4b448f544272780f88c27d"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategySnakeCaseImpl
  dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  api-docs:
    path: /api/words/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    urls:
#      - name: user-service
#        url: /api/users/v3/api-docs
#      - name: log-service
#        url: /api/logs/v3/api-docs
      - name: kid-service
        url: /api/kids/v3/api-docs
      - name: word-service
        url: /api/words/v3/api-docs
#      - name: game-service
#        url: /api/games/v3/api-docs
#      - name: collection-service
#        url: /api/collections/v3/api-docs
#      - name: probability-service
#        url: /api/probability/v3/api-docs
    paths-to-match: /**